version: '3.6'
services:
  postgres:
    image: postgres:11.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DBNAME}
    ports:
      - '${DB_PORT:-5432}:5432'

volumes:
  postgres_data:
